### ISSUE TITLE
NPE from plugin

### ISSUE THREAD

**Issue by Nightfirecat** [leejt/osrs-wiki-crowdsourcing#31]
I only see it in my logs once, and I don't remember anything odd happening at that time--I was traveling toward Taverley at the time according to my logs--but I did have it happen to me on May 29th. (3 days ago)

```
2022-05-29 15:11:34 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.api.coords.WorldPoint.fromLocalInstance(WorldPoint.java:217)
	at net.runelite.api.coords.WorldPoint.fromLocalInstance(WorldPoint.java:175)
	at com.Crowdsourcing.scenery.CrowdsourcingScenery.addObjectThisTick(CrowdsourcingScenery.java:81)
	at com.Crowdsourcing.scenery.CrowdsourcingScenery.onWallObjectSpawned(CrowdsourcingScenery.java:98)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
	at gn.sw(gn.java:38111)
	at gm.r(gm.java:239)
	at po.f(po.java:1065)
	at hj.hj(hj.java:7958)
	at bn.hp(bn.java:7910)
	at client.ft(client.java:3271)
	at client.ag(client.java:1054)
	at aj.h(aj.java:368)
	at aj.run(aj.java:347)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Nightfirecat** [comment]
Since opening this, I've started to see this error many more times in my logs.

**Comment by andmcadams** [comment]
I'll take a look at this tomorrow, thanks for raising it

**Comment by andmcadams** [comment]
Looks like this is because we call `WorldPoint.fromLocalInstance(client, local)` without guaranteeing that the `LocalPoint local` is non-null in the scenery crowdsourcing. The method that creates the local point (`LocalPoint.fromWorld`) seems to do some sort of plane comparison and if the current plane does not match the given world point's plane, it will return null instead of a coord.

I'm not entirely sure how this happens in the first place. Maybe rendering some object on a lower plane? I'll have to try a bit more to repro it. In other instances we just `return` when the local point is null, but if there's a better approach or if there's a legit edgecase we would miss by skipping (for ex do objs spawn on lower planes if you can see them?) that might not be good enough.

**Comment by Nightfirecat** [comment]
You should be able to `return` when the point is null. I wish I knew where this was being caused so it could be reproduced for testing, but I don't know offhand where this was caused.

**Comment by Nightfirecat** [comment]
FYI I'm still seeing this today in a variety of places in the game. If you were to set a conditional breakpoint on the point being null before passing it into `fromLocalInstance()` you might be able to figure out what triggers this. It's creating plenty of log lines in my logs though.
